nama = input("nama kamu siapa")
kelas = input("kamu kelas berapa")
umur = input("kamu umur berapa")
sekolah = input("kamu sekolah dimana")
jurusan = input("kamu jurusan apa")
hobi = input("hobi kamu apa")
citacita = input("citacita kamu apa")
makanan = input("makanan kesukaan kamu apa")
alamat = input("kamu tinggal dimana")
youtuber = input("youtuber faforit kamu siapa")
print("nama saya adalah",nama,"saya kelas",kelas,"umur saya",umur,"saya sekolah di",sekolah,"saya jurusan",jurusan,"hobi saya",hobi,"citacita saya",citacita,"makanan kesukaan saya",makanan,"saya tinggal di",alamat,"youtuber faforit saya",youtuber)